apiVersion: apps/v1
kind: Deployment
metadata:
  name: tc-camel
  namespace: crda
  labels:
    app: tc-camel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tc-camel
  template:
    metadata:
      labels:
        app: tc-camel
    spec:
      containers:
      - name: tc-camel
        image: quay.io/ecosystem-appeng/tc-camel:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tc-camel
  name: tc-camel
  namespace: crda
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tc-camel
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: tc-camel
  name: tc-camel
  namespace: crda
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: tc-camel